# Change these first
owner: Ky4eryavii-Pon4o # Your GitHub organization or username, where this repository lives
repo: web-uptime # The name of this repository

sites:
  - name: IT.Patap
    url: https://it.patap.org.ua
    icon: https://it.patap.org.ua/favicon.png
  - name: Grishchuk
    url: http://grishchuk.com.ua
  - name: ky4eryavii
    url: https://ky4eryavii-pon4o.github.io/
  - name: Neocities
    url: https://patap.neocities.org/
    icon: https://patap.neocities.org/assets/favicon.png
  - name: Patap
    url: https://patap.org.ua

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /web-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Patap Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hi
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://it.patap.org.ua

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
